name: Count Lines and Trigger Deploy

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'

jobs:
  count-lines:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Count lines of code
        run: |
          mkdir -p public
          total=0
          for repo in $(gh repo list gg582 --limit 1000 --json name,isPrivate --jq '.[] | select(.isPrivate == false) | .name'); do
            echo "Cloning $repo..."
            gh repo clone gg582/$repo temp_repo -- --depth=1
            count=$(find temp_repo -type f \( -name '*.c' -o -name '*.cpp' -o -name '*.py' -o -name '*.java' -o -name '*.sh' \) -exec cat {} + | wc -l)
            echo "$repo: $count lines"
            total=$((total + count))
            rm -rf temp_repo
          done
          echo "{\"total_lines\": $total}" > public/lines.json

      - name: Trigger Vercel Deploy Hook
        run: curl -X POST "${{ secrets.VERCEL_HOOK_URL }}"
