name: Calculate Lines and Deploy

on:
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:     

jobs:
  count-lines:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Calculate total lines of code
        id: count
        run: |
          total=$(git ls-files '*.c' '*.cpp' '*.py' '*.go' '*.js' '*.ts' '*.java' '*.cs' '*.rb' | xargs cat | wc -l)
          echo "Total lines: $total"
          echo "::set-output name=total::$total"

      - name: Create JSON badge file
        run: |
          echo "{\"schemaVersion\":1,\"label\":\"Lines\",\"message\":\"${{ steps.count.outputs.total }}\",\"color\":\"blue\"}" > public/lines.json

      - name: Commit and push JSON file
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add public/lines.json
          git commit -m "Update total lines count badge"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

